# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-11 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_location',
            field=models.FileField(max_length=200, upload_to=b''),
        ),
    ]
