# Generated by Django 2.0.6 on 2018-06-13 04:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20180612_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 13, 4, 3, 0, 514349, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_location',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
